apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: musicplayers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                songs:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      url:
                        type: string
                      imageUrl:
                        type: string
  names:
    kind: MusicPlayer
    plural: musicplayers
    singular: musicplayer
  scope: Namespaced
