apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicplayer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicplayer-operator
  template:
    metadata:
      labels:
        app: musicplayer-operator
    spec:
      serviceAccountName: musicplayer-operator
      containers:
      - name: musicplayer-operator
        image: your/musicplayer-operator-image:latest
